import Vue from 'vue'
import { Button,Avatar,Tabs,ag, Tag,Divider,Radio,Image,Drawer,Steps,Step,Popover} from 'element-ui'
import {Form,FormItem,Input,Select,Option,Carousel,CarouselItem,Checkbox,CheckboxGroup,Loading,Alert} from 'element-ui'
import {Message,MessageBox,Container,Header,Main,Aside,Tooltip,Pagination,Menu,Submenu,MenuItemGroup,MenuItem,Breadcrumb,BreadcrumbItem,Card,Row,Dialog,Col,TabPane,Table,TableColumn,Switch} from 'element-ui'
Vue.use(Tabs)
Vue.use(Popover)
Vue.use(Steps)
Vue.use(Step)
Vue.use(Drawer)
Vue.use(Image)
Vue.use(Divider)
Vue.use(Radio)
Vue.use(Tag)
Vue.use(TabPane)
Vue.use(Avatar)
Vue.use(Alert)
Vue.use(Loading)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.use(Pagination)
Vue.use(Tooltip)
Vue.use(Switch)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Select)
Vue.use(Option)
Vue.use(Row)
Vue.use(Col)
Vue.use(Dialog)
Vue.use(Card)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Container)
Vue.use(Header)
Vue.use(Main)
Vue.use(Aside)
Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.prototype.$message=Message
Vue.prototype.$confirm=MessageBox.confirm